# Generated by Django 5.2.1 on 2026-01-26 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriasProductosElaborados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, max_length=255, null=True)),
                ('es_intermediario', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriasProductosReventa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadosOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadosOrdenVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetodosDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_metodo', models.CharField(max_length=100)),
                ('requiere_referencia', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadesDeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=50, unique=True)),
                ('abreviatura', models.CharField(max_length=10)),
                ('descripcion', models.TextField(blank=True, max_length=255, null=True)),
                ('tipo_medida', models.CharField(choices=[('peso', 'Peso'), ('volumen', 'Volumen'), ('unidad', 'Unidad'), ('longitud', 'Longitud'), ('otro', 'Otro')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_notificacion', models.CharField(choices=[('Bajo stock', 'Bajo stock'), ('Sin stock', 'Sin stock'), ('Expiración', 'Expiración'), ('Entrega cercana', 'Entrega cercana')], max_length=50)),
                ('tipo_producto', models.CharField(choices=[('Materia prima', 'Materia prima'), ('Productos finales', 'Productos finales'), ('Productos intermedios', 'Productos intermedios'), ('Productos de reventa', 'Productos de reventa'), ('Ordenes de venta', 'Ordenes de venta')], max_length=50)),
                ('producto_id', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=255, null=True)),
                ('fecha_notificacion', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('prioridad', models.CharField(blank=True, choices=[('Bajo', 'Bajo'), ('Medio', 'Medio'), ('Alto', 'Alto'), ('Crítico', 'Crítico')], max_length=50, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('leida', False)), fields=('tipo_notificacion', 'tipo_producto', 'producto_id', 'prioridad'), name='unique_unread_notification')],
            },
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, max_length=255, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidadesdemedida')),
            ],
        ),
        migrations.CreateModel(
            name='ConversionesUnidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_conversion', models.DecimalField(decimal_places=6, help_text='Factor de conversión: 1 unidad_origen = X unidad_destino', max_digits=15)),
                ('unidad_destino', models.ForeignKey(help_text='Unidad a la cual se convierte', on_delete=django.db.models.deletion.CASCADE, related_name='conversiones_destino', to='core.unidadesdemedida')),
                ('unidad_origen', models.ForeignKey(help_text='Unidad desde la cual se convierte', on_delete=django.db.models.deletion.CASCADE, related_name='conversiones_origen', to='core.unidadesdemedida')),
            ],
            options={
                'verbose_name': 'Conversión de Unidad',
                'verbose_name_plural': 'Conversiones de Unidades',
                'unique_together': {('unidad_origen', 'unidad_destino')},
            },
        ),
    ]
