# Generated by Django 5.2.1 on 2026-04-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificaciones',
            name='variante_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
