# Generated by Django 5.2.1 on 2026-04-13 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notificaciones_variante_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empaques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empaque', models.CharField(max_length=100)),
                ('es_contenedor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmpaquetadoProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_por_contenedor', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('cantidad_unidad_medida', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('empaque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empaques')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidadesdemedida')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad_por_contenedor__gt', 0)), name='check_cantidad_por_contenedor_gt_0'), models.CheckConstraint(condition=models.Q(('cantidad_unidad_medida__gt', 0)), name='check_cantidad_unidad_medida_gt_0')],
            },
        ),
    ]
