# Generated by Django 5.2.1 on 2026-04-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_empaques_empaquetadoproductos'),
    ]

    operations = [
        migrations.AddField(
            model_name='empaques',
            name='tipo_medida',
            field=models.CharField(choices=[('peso', 'Peso'), ('volumen', 'Volumen'), ('unidad', 'Unidad'), ('longitud', 'Longitud'), ('otro', 'Otro')], default='Peso', max_length=10),
            preserve_default=False,
        ),
    ]
