# Generated by Django 5.2.1 on 2026-01-26 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transformacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_transformacion', models.CharField(max_length=255)),
                ('cantidad_origen', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cantidad_destino', models.DecimalField(decimal_places=3, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LotesConsumidosTransformacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_consumida', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cantidad_creada', models.DecimalField(decimal_places=3, max_digits=10)),
                ('lote_producto_elaborado_consumido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_consumidos_transformacion', to='inventario.lotesproductoselaborados')),
                ('lote_producto_elaborado_creado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_creados_transformacion', to='inventario.lotesproductoselaborados')),
                ('transformacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_consumidos', to='transformacion.transformacion')),
            ],
        ),
        migrations.CreateModel(
            name='EjecutarTransformacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True)),
                ('producto_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecutar_transformacion_producto_destino', to='inventario.productoselaboradosvariantes')),
                ('producto_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecutar_transformacion_producto_origen', to='inventario.productoselaboradosvariantes')),
                ('transformacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='transformacion.transformacion')),
            ],
        ),
    ]
