# Generated by Django 5.2.1 on 2026-01-26 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventario', '0002_initial'),
        ('produccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='definiciontransformacion',
            name='usuario_creacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleproduccioncosumos',
            name='materia_prima_consumida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.materiasprimas'),
        ),
        migrations.AddField(
            model_name='detalleproduccioncosumos',
            name='producto_intermedio_consumido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.productoselaboradosvariantes'),
        ),
        migrations.AddField(
            model_name='detalleproduccionlote',
            name='detalle_produccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='produccion.detalleproduccioncosumos'),
        ),
        migrations.AddField(
            model_name='detalleproduccionlote',
            name='lote_materia_prima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.lotesmateriasprimas'),
        ),
        migrations.AddField(
            model_name='detalleproduccionlote',
            name='lote_producto_intermedio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.lotesproductoselaborados'),
        ),
        migrations.AddField(
            model_name='logtransformacion',
            name='definicion_transformacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.definiciontransformacion'),
        ),
        migrations.AddField(
            model_name='logtransformacion',
            name='usuario_creacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produccion',
            name='producto_elaborado_variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productoselaboradosvariantes'),
        ),
        migrations.AddField(
            model_name='produccion',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.unidadesdemedida'),
        ),
        migrations.AddField(
            model_name='produccion',
            name='usuario_creacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleproduccioncosumos',
            name='produccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.produccion'),
        ),
        migrations.AddField(
            model_name='recetas',
            name='producto_elaborado_variante',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receta_producto_elaborado_variante', to='inventario.productoselaboradosvariantes'),
        ),
        migrations.AddField(
            model_name='recetasdetalles',
            name='componente_materia_prima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.materiasprimas'),
        ),
        migrations.AddField(
            model_name='recetasdetalles',
            name='componente_producto_intermedio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receta_componente_producto_intermedio', to='inventario.productoselaboradosvariantes'),
        ),
        migrations.AddField(
            model_name='recetasdetalles',
            name='receta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='produccion.recetas'),
        ),
        migrations.AddField(
            model_name='relacionesrecetas',
            name='receta_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receta_principal', to='produccion.recetas'),
        ),
        migrations.AddField(
            model_name='relacionesrecetas',
            name='subreceta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subreceta', to='produccion.recetas'),
        ),
        migrations.AddConstraint(
            model_name='detalleproduccionlote',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lote_materia_prima__isnull', False), ('lote_producto_intermedio__isnull', True)), models.Q(('lote_materia_prima__isnull', True), ('lote_producto_intermedio__isnull', False)), _connector='OR'), name='un_solo_tipo_lote_en_detalle'),
        ),
        migrations.AddConstraint(
            model_name='detalleproduccioncosumos',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('materia_prima_consumida__isnull', False), ('producto_intermedio_consumido__isnull', True)), models.Q(('materia_prima_consumida__isnull', True), ('producto_intermedio_consumido__isnull', False)), _connector='OR'), name='mp_o_pi_en_detalle'),
        ),
        migrations.AddConstraint(
            model_name='recetasdetalles',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('componente_materia_prima__isnull', False), ('componente_producto_intermedio__isnull', True)), models.Q(('componente_materia_prima__isnull', True), ('componente_producto_intermedio__isnull', False)), _connector='OR'), name='receta_un_solo_tipo_componente'),
        ),
        migrations.AlterUniqueTogether(
            name='recetasdetalles',
            unique_together={('receta', 'componente_materia_prima'), ('receta', 'componente_producto_intermedio')},
        ),
    ]
