# Generated by Django 5.2.1 on 2026-04-01 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_productosreventa_stock_actual'),
        ('produccion', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleproduccioncosumos',
            old_name='costo_consumo_usd',
            new_name='consto_consumo_divisa',
        ),
        migrations.RenameField(
            model_name='detalleproduccionlote',
            old_name='costo_parcial_usd',
            new_name='costo_parcial_divisa',
        ),
        migrations.RenameField(
            model_name='produccion',
            old_name='costo_total_componentes_usd',
            new_name='costo_total_componentes_divisa',
        ),
        migrations.RenameField(
            model_name='produccion',
            old_name='costo_total_componentes_ves',
            new_name='costo_total_componentes_local',
        ),
        migrations.AddField(
            model_name='detalleproduccioncosumos',
            name='consto_consumo_local',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detalleproduccionlote',
            name='costo_parcial_local',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='produccion',
            name='producto_elaborado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventario.productoselaborados'),
            preserve_default=False,
        ),
    ]
