# Generated by Django 5.2.1 on 2026-04-02 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_productosreventa_stock_actual'),
        ('produccion', '0003_rename_costo_consumo_usd_detalleproduccioncosumos_consto_consumo_divisa_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetalleProduccionCosumos',
            new_name='DetalleProduccionConsumos',
        ),
        migrations.RenameField(
            model_name='detalleproduccionconsumos',
            old_name='consto_consumo_divisa',
            new_name='costo_consumo_divisa',
        ),
        migrations.RenameField(
            model_name='detalleproduccionconsumos',
            old_name='consto_consumo_local',
            new_name='costo_consumo_local',
        ),
    ]
