# Generated by Django 5.2.1 on 2026-01-26 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotesProductosElaborados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_inicial_lote', models.DecimalField(decimal_places=2, default=0, help_text='Cantidad original producida en este lote (copiado de Produccion.cantidad_producida)', max_digits=10)),
                ('stock_actual_lote', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_produccion', models.DateField(auto_now_add=True)),
                ('fecha_caducidad', models.DateField()),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible para uso'), ('EXPIRADO', 'Expirado'), ('AGOTADO', 'Agotado'), ('INACTIVO', 'Inactivo')], default='DISPONIBLE', max_length=10)),
                ('coste_total_lote_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('peso_total_lote_gramos', models.DecimalField(blank=True, decimal_places=2, help_text='Actual measured weight of entire batch in grams', max_digits=10, null=True)),
                ('volumen_total_lote_ml', models.DecimalField(blank=True, decimal_places=2, help_text='Actual measured volume of entire batch in milliliters', max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Lote de Producto Elaborado',
                'verbose_name_plural': 'Lotes de Productos Elaborados',
                'ordering': ['fecha_caducidad', '-fecha_produccion'],
            },
        ),
        migrations.CreateModel(
            name='LotesProductosReventa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateField()),
                ('fecha_caducidad', models.DateField()),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_actual_lote', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('coste_unitario_lote_divisa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('coste_unitario_lote_local', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible para uso'), ('EXPIRADO', 'Expirado'), ('AGOTADO', 'Agotado'), ('INACTIVO', 'Inactivo')], default='DISPONIBLE', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MateriasPrimas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('punto_reorden', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('descripcion', models.TextField(blank=True, max_length=255, null=True)),
                ('fecha_creacion_registro', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MateriasPrimasVariantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_variante', models.CharField(max_length=100)),
                ('precio_compra_divisa', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('precio_compra_local', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('nombre_empaque_estandar', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad_empaque_estandar', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductosElaborados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, max_length=255, null=True)),
                ('fecha_creacion_registro', models.DateField(auto_now_add=True)),
                ('fecha_modificacion_registro', models.DateField(auto_now=True)),
                ('vendible_por_medida_real', models.BooleanField(blank=True, help_text='Si es True, el precio final se calcula midiendo peso/volumen en la venta.', null=True)),
                ('tipo_medida_fisica', models.CharField(choices=[('UNIDAD', 'Unidad'), ('PESO', 'Peso'), ('VOLUMEN', 'Volumen')], default='PESO', max_length=10)),
                ('es_intermediario', models.BooleanField(default=False)),
                ('usado_en_transformaciones', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductosElaboradosVariantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_variante', models.CharField(help_text="Nombre descriptivo de la variante (ej: '6 unidades', 'Grande', 'Chocolate')", max_length=100)),
                ('precio_venta_divisa', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('precio_venta_local', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('costo_divisa', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('costo_local', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('SKU', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('descripcion', models.TextField(blank=True, max_length=255, null=True)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('punto_reorden', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('atributo', models.CharField(choices=[('Cantidad', 'Cantidad'), ('Tamaño', 'Tamaño'), ('Sabor', 'Sabor'), ('Color', 'Color')], default='Cantidad', help_text='Tipo de atributo que diferencia esta variante', max_length=100)),
                ('is_vendible', models.BooleanField(default=True, help_text='Si es True, esta variante puede ser vendida')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Variante de Producto Elaborado',
                'verbose_name_plural': 'Variantes de Productos Elaborados',
            },
        ),
        migrations.CreateModel(
            name='ProductosReventa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, max_length=255, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('factor_conversion', models.DecimalField(decimal_places=4, default=1, help_text='Cuántas unidades de inventario equivalen a 1 unidad de venta', max_digits=10)),
                ('fecha_creacion_registro', models.DateField(auto_now_add=True)),
                ('fecha_modificacion_registro', models.DateField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductosReventaVariantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_variante', models.CharField(help_text="Nombre descriptivo de la variante (ej: '6 unidades', 'Grande', 'Chocolate')", max_length=100)),
                ('es_pecedero', models.BooleanField(default=False, help_text='Si es True, esta variante es un pecedero')),
                ('precio_venta_divisa', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('precio_venta_local', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('costo_divisa', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('costo_local', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('SKU', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('descripcion', models.TextField(blank=True, max_length=255, null=True)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('punto_reorden', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('atributo', models.CharField(choices=[('Cantidad', 'Cantidad'), ('Tamaño', 'Tamaño'), ('Sabor', 'Sabor'), ('Color', 'Color')], default='Cantidad', help_text='Tipo de atributo que diferencia esta variante', max_length=100)),
                ('is_vendible', models.BooleanField(default=True, help_text='Si es True, esta variante puede ser vendida')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Variante de Producto Reventa',
                'verbose_name_plural': 'Variantes de Productos Reventa',
            },
        ),
        migrations.CreateModel(
            name='GruposProductosElaborados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, help_text='Cantidad de esta variante incluida en el grupo', max_digits=10)),
                ('descripcion', models.TextField(blank=True, max_length=255, null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_elaborados', to='core.grupos')),
            ],
            options={
                'verbose_name': 'Producto en Grupo',
                'verbose_name_plural': 'Productos en Grupos',
            },
        ),
        migrations.CreateModel(
            name='GruposProductosReventa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('descripcion', models.TextField(blank=True, max_length=255, null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_reventa', to='core.grupos')),
            ],
            options={
                'verbose_name': 'Grupo de Variantes de Productos Reventa',
                'verbose_name_plural': 'Grupos de Variantes de Productos Reventa',
            },
        ),
        migrations.CreateModel(
            name='LotesMateriasPrimas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateField()),
                ('fecha_caducidad', models.DateField()),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_actual_lote', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_unitario_divisa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_unitario_local', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible para uso'), ('EXPIRADO', 'Expirado'), ('AGOTADO', 'Agotado'), ('INACTIVO', 'Inactivo')], default='DISPONIBLE', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('detalle_oc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.detalleordenescompra')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.proveedores')),
            ],
        ),
    ]
