# Generated by Django 5.2.1 on 2026-01-26 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('core', '0001_initial'),
        ('inventario', '0001_initial'),
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotesproductoselaborados',
            name='produccion_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_productos_elaborados', to='produccion.produccion'),
        ),
        migrations.AddField(
            model_name='lotesproductosreventa',
            name='detalle_oc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.detalleordenescompra'),
        ),
        migrations.AddField(
            model_name='lotesproductosreventa',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.proveedores'),
        ),
        migrations.AddField(
            model_name='materiasprimas',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriasmateriaprima'),
        ),
        migrations.AddField(
            model_name='materiasprimas',
            name='unidad_medida_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_primas_unidad_base', to='core.unidadesdemedida'),
        ),
        migrations.AddField(
            model_name='materiasprimasvariantes',
            name='materia_prima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.materiasprimas'),
        ),
        migrations.AddField(
            model_name='materiasprimasvariantes',
            name='unidad_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidadesdemedida'),
        ),
        migrations.AddField(
            model_name='materiasprimasvariantes',
            name='unidad_medida_empaque_estandar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materias_primas_empaque', to='core.unidadesdemedida'),
        ),
        migrations.AddField(
            model_name='lotesmateriasprimas',
            name='variante_materia_prima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.materiasprimasvariantes'),
        ),
        migrations.AddField(
            model_name='productoselaborados',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriasproductoselaborados'),
        ),
        migrations.AddField(
            model_name='productoselaborados',
            name='unidad_produccion',
            field=models.ForeignKey(blank=True, help_text='Unidad en la que se produce y se gestiona el stock (e.g., Unidades, uGramos).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_elaborados_unidad_produccion', to='core.unidadesdemedida'),
        ),
        migrations.AddField(
            model_name='productoselaborados',
            name='unidad_venta',
            field=models.ForeignKey(blank=True, help_text='Unidad en la que se vende el producto (e.g., Unidades, Kilogramos, Litros).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_elaborados_unidad_venta', to='core.unidadesdemedida'),
        ),
        migrations.CreateModel(
            name='ProductosFinales',
            fields=[
            ],
            options={
                'verbose_name': 'Producto Final',
                'verbose_name_plural': 'Productos Finales',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventario.productoselaborados',),
        ),
        migrations.CreateModel(
            name='ProductosIntermedios',
            fields=[
            ],
            options={
                'verbose_name': 'Producto Intermedio',
                'verbose_name_plural': 'Productos Intermedios',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventario.productoselaborados',),
        ),
        migrations.AddField(
            model_name='productoselaboradosvariantes',
            name='producto_elaborado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='inventario.productoselaborados'),
        ),
        migrations.AddField(
            model_name='lotesproductoselaborados',
            name='producto_elaborado_variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='inventario.productoselaboradosvariantes'),
        ),
        migrations.AddField(
            model_name='gruposproductoselaborados',
            name='producto_elaborado_variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='inventario.productoselaboradosvariantes'),
        ),
        migrations.AddField(
            model_name='productosreventa',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriasproductosreventa'),
        ),
        migrations.AddField(
            model_name='productosreventa',
            name='proveedor_preferido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.proveedores'),
        ),
        migrations.AddField(
            model_name='productosreventa',
            name='unidad_base_inventario',
            field=models.ForeignKey(blank=True, help_text='Unidad en la que se gestiona el stock (ej: Unidad para latas, Gramos para jamón)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_reventa_inventario', to='core.unidadesdemedida'),
        ),
        migrations.AddField(
            model_name='productosreventa',
            name='unidad_venta',
            field=models.ForeignKey(blank=True, help_text='Unidad en la que se vende el producto (ej: Unidad para bolsa de 1kg)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_reventa_venta', to='core.unidadesdemedida'),
        ),
        migrations.AddField(
            model_name='productosreventavariantes',
            name='producto_reventa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='inventario.productosreventa'),
        ),
        migrations.AddField(
            model_name='lotesproductosreventa',
            name='producto_reventa_variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productosreventavariantes'),
        ),
        migrations.AddField(
            model_name='gruposproductosreventa',
            name='producto_reventa_variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productosreventavariantes'),
        ),
        migrations.AddConstraint(
            model_name='productoselaborados',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('es_intermediario', True), ('unidad_venta__isnull', True), ('vendible_por_medida_real__isnull', True)), models.Q(('es_intermediario', False), ('unidad_venta__isnull', False), ('vendible_por_medida_real__isnull', False)), _connector='OR'), name='intermedio_o_producto'),
        ),
        migrations.AlterUniqueTogether(
            name='productoselaboradosvariantes',
            unique_together={('producto_elaborado', 'nombre_variante')},
        ),
        migrations.AlterUniqueTogether(
            name='gruposproductoselaborados',
            unique_together={('producto_elaborado_variante', 'grupo')},
        ),
        migrations.AlterUniqueTogether(
            name='productosreventavariantes',
            unique_together={('producto_reventa', 'nombre_variante')},
        ),
        migrations.AlterUniqueTogether(
            name='gruposproductosreventa',
            unique_together={('producto_reventa_variante', 'grupo')},
        ),
    ]
