# Generated by Django 5.2.1 on 2026-01-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiasprimas',
            name='SKU',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='materiasprimasvariantes',
            name='SKU_variante',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
