# Generated by Django 5.2.1 on 2026-03-04 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_materiasprimas_sku_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoselaborados',
            name='fecha_modificacion_registro',
        ),
        migrations.RemoveField(
            model_name='productoselaboradosvariantes',
            name='fecha_modificacion',
        ),
        migrations.AlterField(
            model_name='materiasprimasvariantes',
            name='materia_prima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='inventario.materiasprimas'),
        ),
    ]
