# Generated by Django 5.2.1 on 2026-03-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_productoselaborados_fecha_modificacion_registro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productosreventa',
            name='fecha_modificacion_registro',
        ),
        migrations.RemoveField(
            model_name='productosreventavariantes',
            name='es_pecedero',
        ),
        migrations.AddField(
            model_name='productosreventa',
            name='es_pecedero',
            field=models.BooleanField(default=False, help_text='Si es True, esta variante es un pecedero'),
        ),
    ]
