# Generated by Django 5.2.1 on 2026-03-13 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_remove_productosreventa_fecha_modificacion_registro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productosreventa',
            old_name='es_pecedero',
            new_name='es_perecedero',
        ),
    ]
