# Generated by Django 5.2.1 on 2026-03-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_rename_es_pecedero_productosreventa_es_perecedero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotesproductosreventa',
            name='fecha_caducidad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productosreventa',
            name='es_perecedero',
            field=models.BooleanField(default=False, help_text='Si es True, esta variante es un perecedero'),
        ),
    ]
