# Generated by Django 5.2.1 on 2026-03-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_lotesproductosreventa_fecha_caducidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosreventa',
            name='stock_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
