# Generated by Django 5.2.1 on 2026-04-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_productosreventa_stock_actual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lotesproductoselaborados',
            old_name='coste_total_lote_usd',
            new_name='coste_total_lote_divisa',
        ),
        migrations.AddField(
            model_name='lotesproductoselaborados',
            name='coste_total_lote_local',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
