# Generated by Django 5.2.1 on 2026-04-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_rename_coste_total_lote_usd_lotesproductoselaborados_coste_total_lote_divisa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoselaborados',
            name='stock_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
