# Generated by Django 5.2.1 on 2026-04-15 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_productoselaborados_stock_actual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productosreventa',
            old_name='unidad_base_inventario',
            new_name='unidad_medida_base',
        ),
    ]
