# Generated by Django 5.2.1 on 2026-09-21 14:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_rename_unidad_base_inventario_productosreventa_unidad_medida_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotesmateriasprimas',
            name='cantidad_recibida',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='lotesmateriasprimas',
            name='costo_unitario_divisa',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='lotesmateriasprimas',
            name='costo_unitario_local',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='lotesmateriasprimas',
            name='stock_actual_lote',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='materiasprimas',
            name='punto_reorden',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='materiasprimas',
            name='stock_actual',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='materiasprimasvariantes',
            name='cantidad_empaque_estandar',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.00'), max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='materiasprimasvariantes',
            name='precio_compra_divisa',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.00'), max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='materiasprimasvariantes',
            name='precio_compra_local',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.00'), max_digits=20, null=True),
        ),
    ]
