# Generated by Django 5.2.1 on 2026-01-26 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventario', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('apellido_cliente', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('rif_cedula', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AperturaCierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_inicial_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_inicial_ves', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_final_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_final_ves', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_efectivo_usd', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('total_efectivo_ves', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('total_tarjeta_usd', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('total_tarjeta_ves', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('total_transferencia_usd', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('total_transferencia_ves', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('total_pago_movil_usd', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('total_pago_movil_ves', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('total_cambio_efectivo_usd', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('total_cambio_efectivo_ves', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('total_cambio_pago_movil_usd', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('total_cambio_pago_movil_ves', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('total_cambio_usd', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('total_cambio_ves', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('total_ventas_usd', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('total_ventas_ves', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('diferencia_usd', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('diferencia_ves', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('notas_apertura', models.TextField(blank=True, null=True)),
                ('notas_cierre', models.TextField(blank=True, null=True)),
                ('esta_activa', models.BooleanField(default=True)),
                ('usuario_apertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aperturas_realizadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cierres_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Apertura/Cierre de Caja',
                'verbose_name_plural': 'Aperturas/Cierres de Caja',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='DetallesOrdenVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.DecimalField(decimal_places=3, max_digits=10)),
                ('precio_unitario_usd', models.DecimalField(decimal_places=3, max_digits=10)),
                ('precio_unitario_ves', models.DecimalField(decimal_places=3, max_digits=10)),
                ('subtotal_linea_usd', models.DecimalField(decimal_places=3, max_digits=10)),
                ('subtotal_linea_ves', models.DecimalField(decimal_places=3, max_digits=10)),
                ('descuento_porcentaje', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('impuesto_porcentaje', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('producto_elaborado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.productoselaboradosvariantes')),
                ('producto_reventa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.productosreventavariantes')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidadesdemedida')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenConsumoLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('detalle_orden_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.detallesordenventa')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenConsumoLoteDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_consumida', models.DecimalField(decimal_places=3, max_digits=10)),
                ('costo_parcial_usd', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('costo_parcial_ves', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('lote_producto_elaborado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.lotesproductoselaborados')),
                ('lote_producto_reventa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.lotesproductosreventa')),
                ('orden_consumo_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_lotes', to='ventas.ordenconsumolote')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion_orden', models.DateField()),
                ('fecha_entrega_solicitada', models.DateField()),
                ('fecha_entrega_definitiva', models.DateField(blank=True, null=True)),
                ('notas_generales', models.TextField(blank=True, max_length=255, null=True)),
                ('monto_descuento_usd', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('monto_descuento_ves', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('monto_impuestos_usd', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('monto_impuestos_ves', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('monto_total_usd', models.DecimalField(decimal_places=3, max_digits=10)),
                ('monto_total_ves', models.DecimalField(decimal_places=3, max_digits=10)),
                ('tasa_cambio_aplicada', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.clientes')),
                ('estado_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estadosordenventa')),
                ('metodo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.metodosdepago')),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ordenconsumolote',
            name='orden_venta_asociada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_lotes_orden_venta', to='ventas.ordenventa'),
        ),
        migrations.AddField(
            model_name='detallesordenventa',
            name='orden_venta_asociada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='ventas.ordenventa'),
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField()),
                ('monto_total_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_total_ves', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tasa_cambio_aplicada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notas', models.TextField(blank=True, max_length=255, null=True)),
                ('apertura_caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.aperturacierrecaja')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.clientes')),
                ('usuario_cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pago_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_pago_ves', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField()),
                ('referencia_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('cambio_efectivo_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cambio_efectivo_ves', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cambio_pago_movil_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cambio_pago_movil_ves', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tasa_cambio_aplicada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notas', models.TextField(blank=True, max_length=255, null=True)),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.metodosdepago')),
                ('orden_venta_asociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.ordenventa')),
                ('usuario_registrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venta_asociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.ventas')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_vendida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('precio_unitario_ves', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('subtotal_linea_usd', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('subtotal_linea_ves', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('producto_elaborado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.productoselaboradosvariantes')),
                ('producto_reventa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.productosreventavariantes')),
                ('unidad_medida_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.unidadesdemedida')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.ventas')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
            },
        ),
        migrations.CreateModel(
            name='VentasLotesVendidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_consumida', models.DecimalField(decimal_places=3, max_digits=10)),
                ('fecha_consumo', models.DateTimeField(auto_now_add=True)),
                ('detalle_venta_asociada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_vendidos', to='ventas.detalleventa')),
                ('lote_producto_elaborado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.lotesproductoselaborados')),
                ('lote_producto_reventa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.lotesproductosreventa')),
            ],
        ),
        migrations.AddConstraint(
            model_name='aperturacierrecaja',
            constraint=models.UniqueConstraint(condition=models.Q(('esta_activa', True)), fields=('esta_activa',), name='solo_una_caja_activa'),
        ),
        migrations.AddConstraint(
            model_name='ordenconsumolotedetalle',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lote_producto_elaborado__isnull', False), ('lote_producto_reventa__isnull', True)), models.Q(('lote_producto_elaborado__isnull', True), ('lote_producto_reventa__isnull', False)), _connector='OR'), name='detalle_orden_consumo_lote_un_solo_tipo_de_producto'),
        ),
        migrations.AddConstraint(
            model_name='detallesordenventa',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('producto_elaborado__isnull', False), ('producto_reventa__isnull', True)), models.Q(('producto_elaborado__isnull', True), ('producto_reventa__isnull', False)), _connector='OR'), name='detalle_orden_venta_un_solo_tipo_de_producto'),
        ),
        migrations.AddConstraint(
            model_name='pagos',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('venta_asociada__isnull', False), ('orden_venta_asociada__isnull', True)), models.Q(('venta_asociada__isnull', True), ('orden_venta_asociada__isnull', False)), _connector='OR'), name='un_solo_tipo_de_venta_por_pago'),
        ),
        migrations.AddConstraint(
            model_name='detalleventa',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('producto_elaborado__isnull', False), ('producto_reventa__isnull', True)), models.Q(('producto_elaborado__isnull', True), ('producto_reventa__isnull', False)), _connector='OR'), name='detalle_venta_un_solo_tipo_de_producto'),
        ),
        migrations.AddConstraint(
            model_name='ventaslotesvendidos',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lote_producto_elaborado__isnull', False), ('lote_producto_reventa__isnull', True)), models.Q(('lote_producto_elaborado__isnull', True), ('lote_producto_reventa__isnull', False)), _connector='OR'), name='venta_lotes_vendidos_un_solo_tipo'),
        ),
    ]
