# Generated by Django 5.2.1 on 2026-01-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagado', models.BooleanField(default=False, help_text='Indica si esta recepción ha sido pagada completamente')),
                ('monto_pendiente_pago_usd', models.DecimalField(decimal_places=3, default=0, help_text='Monto pendiente de pago en USD', max_digits=15)),
                ('fecha_recepcion', models.DateField(help_text='Fecha en que se recibió la mercancía')),
                ('numero_factura_proveedor', models.CharField(blank=True, help_text='Número de factura del proveedor para esta entrega', max_length=100, null=True)),
                ('numero_remision', models.CharField(blank=True, help_text='Número de guía de remisión o nota de entrega', max_length=100, null=True)),
                ('monto_recepcion_usd', models.DecimalField(decimal_places=3, default=0, help_text='Monto total de esta recepción en USD', max_digits=15)),
                ('monto_recepcion_ves', models.DecimalField(decimal_places=3, default=0, help_text='Monto total de esta recepción en VES', max_digits=15)),
                ('tasa_cambio_aplicada', models.DecimalField(decimal_places=3, default=0, help_text='Tasa de cambio USD/VES al momento de la recepción', max_digits=15)),
                ('notas', models.TextField(blank=True, help_text='Observaciones sobre la recepción', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compra/Recepción',
                'verbose_name_plural': 'Compras/Recepciones',
                'ordering': ['-fecha_recepcion', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, help_text='Cantidad recibida en esta entrega', max_digits=10)),
                ('costo_unitario_usd', models.DecimalField(decimal_places=2, help_text='Costo unitario en USD', max_digits=10)),
                ('subtotal_usd', models.DecimalField(decimal_places=2, help_text='Subtotal de esta línea (cantidad * costo_unitario)', max_digits=10)),
                ('notas', models.TextField(blank=True, help_text='Observaciones sobre este producto recibido', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalles de Compra',
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenesCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('cantidad_recibida', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('costo_unitario_usd', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('subtotal_linea_usd', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenesCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision_oc', models.DateField()),
                ('fecha_entrega_esperada', models.DateField()),
                ('fecha_entrega_real', models.DateField(blank=True, null=True)),
                ('monto_total_oc_usd', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('monto_total_oc_ves', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('tasa_cambio_aplicada', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('direccion_envio', models.TextField(blank=True, max_length=255, null=True)),
                ('fecha_envio_oc', models.DateField(blank=True, null=True)),
                ('email_enviado', models.BooleanField(default=False)),
                ('fecha_email_enviado', models.DateTimeField(blank=True, null=True)),
                ('terminos_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('notas', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PagosProveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(help_text='Fecha en que se realizó el pago')),
                ('monto_pago_usd', models.DecimalField(decimal_places=3, help_text='Monto pagado en USD', max_digits=10)),
                ('monto_pago_ves', models.DecimalField(decimal_places=3, help_text='Monto pagado en VES', max_digits=10)),
                ('tasa_cambio_aplicada', models.DecimalField(decimal_places=3, help_text='Tasa de cambio USD/VES al momento del pago', max_digits=10)),
                ('referencia_pago', models.CharField(blank=True, help_text='Número de referencia de transferencia/transacción', max_length=100, null=True)),
                ('numero_comprobante', models.CharField(blank=True, help_text='Número de comprobante de pago', max_length=100, null=True)),
                ('notas', models.TextField(blank=True, help_text='Observaciones sobre el pago', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pago a Proveedor',
                'verbose_name_plural': 'Pagos a Proveedores',
                'ordering': ['-fecha_pago', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('apellido_proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_comercial', models.CharField(blank=True, max_length=100, null=True)),
                ('email_contacto', models.EmailField(blank=True, max_length=100, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion_registro', models.DateField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
