# Generated by Django 5.2.1 on 2026-01-26 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('core', '0001_initial'),
        ('inventario', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='usuario_recepcionador',
            field=models.ForeignKey(help_text='Usuario que registró la recepción de mercancía', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallecompras',
            name='compra',
            field=models.ForeignKey(help_text='Compra/recepción a la que pertenece este detalle', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.compras'),
        ),
        migrations.AddField(
            model_name='detallecompras',
            name='unidad_medida',
            field=models.ForeignKey(help_text='Unidad de medida de la cantidad recibida', on_delete=django.db.models.deletion.CASCADE, to='core.unidadesdemedida'),
        ),
        migrations.AddField(
            model_name='detallecompras',
            name='variante_materia_prima',
            field=models.ForeignKey(blank=True, help_text='Materia prima recibida', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.materiasprimasvariantes'),
        ),
        migrations.AddField(
            model_name='detallecompras',
            name='variante_producto_reventa',
            field=models.ForeignKey(blank=True, help_text='Producto de reventa recibido', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.productosreventavariantes'),
        ),
        migrations.AddField(
            model_name='detalleordenescompra',
            name='unidad_medida_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidadesdemedida'),
        ),
        migrations.AddField(
            model_name='detalleordenescompra',
            name='variante_materia_prima',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.materiasprimasvariantes'),
        ),
        migrations.AddField(
            model_name='detalleordenescompra',
            name='variante_producto_reventa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.productosreventavariantes'),
        ),
        migrations.AddField(
            model_name='detallecompras',
            name='detalle_oc',
            field=models.ForeignKey(help_text='Línea de la OC correspondiente a este producto', on_delete=django.db.models.deletion.CASCADE, to='compras.detalleordenescompra'),
        ),
        migrations.AddField(
            model_name='ordenescompra',
            name='estado_oc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estadosordencompra'),
        ),
        migrations.AddField(
            model_name='ordenescompra',
            name='metodo_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.metodosdepago'),
        ),
        migrations.AddField(
            model_name='ordenescompra',
            name='usuario_creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleordenescompra',
            name='orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.ordenescompra'),
        ),
        migrations.AddField(
            model_name='compras',
            name='orden_compra',
            field=models.ForeignKey(help_text='Orden de compra asociada a esta recepción', on_delete=django.db.models.deletion.CASCADE, related_name='recepciones', to='compras.ordenescompra'),
        ),
        migrations.AddField(
            model_name='pagosproveedores',
            name='compra_asociada',
            field=models.ForeignKey(blank=True, help_text='Compra/recepción específica a la que se aplica este pago', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='compras.compras'),
        ),
        migrations.AddField(
            model_name='pagosproveedores',
            name='metodo_pago',
            field=models.ForeignKey(help_text='Método utilizado para el pago', on_delete=django.db.models.deletion.CASCADE, to='core.metodosdepago'),
        ),
        migrations.AddField(
            model_name='pagosproveedores',
            name='orden_compra_asociada',
            field=models.ForeignKey(blank=True, help_text='Orden de compra a la que se aplica este pago', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='compras.ordenescompra'),
        ),
        migrations.AddField(
            model_name='pagosproveedores',
            name='usuario_registrador',
            field=models.ForeignKey(help_text='Usuario que registró el pago', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagosproveedores',
            name='proveedor',
            field=models.ForeignKey(help_text='Proveedor al que se realiza el pago', on_delete=django.db.models.deletion.CASCADE, to='compras.proveedores'),
        ),
        migrations.AddField(
            model_name='ordenescompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.proveedores'),
        ),
        migrations.AddField(
            model_name='compras',
            name='proveedor',
            field=models.ForeignKey(help_text='Proveedor que realizó la entrega', on_delete=django.db.models.deletion.CASCADE, to='compras.proveedores'),
        ),
        migrations.AddConstraint(
            model_name='detallecompras',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('variante_materia_prima__isnull', False), ('variante_producto_reventa__isnull', True)), models.Q(('variante_materia_prima__isnull', True), ('variante_producto_reventa__isnull', False)), _connector='OR'), name='detalle_compra_un_solo_tipo_de_producto'),
        ),
        migrations.AddConstraint(
            model_name='detalleordenescompra',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('variante_materia_prima__isnull', False), ('variante_producto_reventa__isnull', True)), models.Q(('variante_materia_prima__isnull', True), ('variante_producto_reventa__isnull', False)), _connector='OR'), name='detalle_orden_compra_un_solo_tipo_de_producto'),
        ),
    ]
