# Generated by Django 5.2.1 on 2026-04-20 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_initial'),
        ('core', '0004_empaques_tipo_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleordenescompra',
            name='costo_unitario_ves',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='detalleordenescompra',
            name='subtotal_linea_ves',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='detalleordenescompra',
            name='unidad_empaquetado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empaquetadoproductos'),
        ),
    ]
