# Generated by Django 5.2.1 on 2026-04-21 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_detalleordenescompra_costo_unitario_ves_and_more'),
        ('core', '0004_empaques_tipo_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleordenescompra',
            name='unidad_empaquetado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empaquetadoproductos'),
        ),
        migrations.AlterField(
            model_name='detalleordenescompra',
            name='unidad_medida_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.unidadesdemedida'),
        ),
    ]
