# Generated by Django 5.2.1 on 2026-09-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_alter_detalleordenescompra_unidad_empaquetado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='monto_pendiente_pago_usd',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Monto pendiente de pago en USD', max_digits=15),
        ),
        migrations.AlterField(
            model_name='compras',
            name='monto_recepcion_usd',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Monto total de esta recepción en USD', max_digits=15),
        ),
        migrations.AlterField(
            model_name='compras',
            name='monto_recepcion_ves',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Monto total de esta recepción en VES', max_digits=15),
        ),
        migrations.AlterField(
            model_name='compras',
            name='tasa_cambio_aplicada',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Tasa de cambio USD/VES al momento de la recepción', max_digits=15),
        ),
        migrations.AlterField(
            model_name='detallecompras',
            name='cantidad_recibida',
            field=models.DecimalField(decimal_places=4, help_text='Cantidad recibida en esta entrega', max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallecompras',
            name='costo_unitario_usd',
            field=models.DecimalField(decimal_places=4, help_text='Costo unitario en USD', max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallecompras',
            name='subtotal_usd',
            field=models.DecimalField(decimal_places=4, help_text='Subtotal de esta línea (cantidad * costo_unitario)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='detalleordenescompra',
            name='cantidad_recibida',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='detalleordenescompra',
            name='cantidad_solicitada',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='detalleordenescompra',
            name='costo_unitario_usd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='detalleordenescompra',
            name='costo_unitario_ves',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='detalleordenescompra',
            name='subtotal_linea_usd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='detalleordenescompra',
            name='subtotal_linea_ves',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='ordenescompra',
            name='monto_total_oc_usd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='ordenescompra',
            name='monto_total_oc_ves',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='ordenescompra',
            name='tasa_cambio_aplicada',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='pagosproveedores',
            name='monto_pago_usd',
            field=models.DecimalField(decimal_places=4, help_text='Monto pagado en USD', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pagosproveedores',
            name='monto_pago_ves',
            field=models.DecimalField(decimal_places=4, help_text='Monto pagado en VES', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pagosproveedores',
            name='tasa_cambio_aplicada',
            field=models.DecimalField(decimal_places=4, help_text='Tasa de cambio USD/VES al momento del pago', max_digits=10),
        ),
    ]
